# マウスでウィンドウ・ペインの切り替えやリサイズを可能にする
set-option -g mouse on    
# マウスホイールでヒストリではなくスクロールできるようにする
set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
# カラースキーム
set -g default-terminal "screen-256color"
setw -g mode-keys vi
# 'v で選択開始
bind -T copy-mode-vi v send -X begin-selection
# 'V' で行選択
bind -T copy-mode-vi V send -X select-line
# 'C-v' で矩形選択
bind -T copy-mode-vi C-v send -X rectangle-toggle
# 'y' でヤンク
bind -T copy-mode-vi y send -X copy-selection
# 'Y' で行ヤンク
bind -T copy-mode-vi Y send -X copy-line
# Ctrl+tでタブを開く
bind -n C-t new-window -a -c "#{pane_current_path}"
# Alt+|で左右に分割,Alt+-で上下に分割
bind -n 'C-\' split-window -h -c "#{pane_current_path}"
bind -n C-- split-window -v -c "#{pane_current_path}"
# C-wで分割した画面を消す
bind -n C-w kill-pane
# 同じキーバインドでタブを開く
bind -n C-Pageup \
  if-shell -F '#{==:#{pane_index},1}' \
  'previous-window; run "tmux select-pane -t $(tmux list-panes | wc -l)"' \
  'select-pane -t :.-'
bind -n C-Pagedown \
  if-shell -F '#{==:#{pane_index},#{window_panes}}' \
  'next-window; select-pane -t 1' \
  'select-pane -t :.+'
# update-notifier-commonパッケージが必須
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'arcticicestudio/nord-tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
