[[plugins]]
repo = "lewis6991/impatient.nvim"
[[plugins]]
repo = "Shougo/dein.vim"
[[plugins]]
repo = "kyazdani42/nvim-web-devicons"
[[plugins]]
repo = "onsails/lspkind.nvim"
[[plugins]]
repo = "nvim-lua/plenary.nvim"

# lsp

[[plugins]]
repo = "williamboman/mason.nvim"

[[plugins]]
repo = "williamboman/mason-lspconfig.nvim"

[[plugins]]
repo = "neovim/nvim-lspconfig"
lua_add = '''
require "modules.completion.lspconfig"
'''

[[plugins]]
repo = "glepnir/lspsaga.nvim"
lua_add = '''
require "modules.completion.lspsaga"
'''
# cmp

[[plugins]]
repo = "hrsh7th/nvim-cmp"
[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp"
[[plugins]]
repo = "hrsh7th/cmp-buffer"
[[plugins]]
repo = "hrsh7th/cmp-path"
[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp-signature-help"
[[plugins]]
repo = "hrsh7th/cmp-nvim-lua"
[[plugins]]
repo = "hrsh7th/cmp-cmdline"
lua_add = '''
require "modules.completion.cmp"
'''
[[plugins]]
repo = "saadparwaiz1/cmp_luasnip"
#スニペット
[[plugins]]
repo = "L3MON4D3/LuaSnip"
on_event = "InsertEnter"
lua_add = '''
require "modules.completion.luasnip"
'''

[[plugins]]
repo = "b0o/schemastore.nvim"
[[plugins]]
repo = "jose-elias-alvarez/null-ls.nvim"
depends = "plenary.nvim"
lua_add = '''
require "modules.completion.null-ls"
'''

#treesitter
[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
lua_add = '''
require "modules.editor.treesitter"
'''
# インデント
[[plugins]]
repo = "lukas-reineke/indent-blankline.nvim"
depends = "nvim-treesitter"
lua_add = '''
require "modules.editor.indent_blankline"
'''
# htmlのタグ
[[plugins]]
repo = "windwp/nvim-ts-autotag"
depends = "nvim-treesitter"

#括弧の色
[[plugins]]
repo = "p00f/nvim-ts-rainbow"
depends = "nvim-treesitter"

[[plugins]]
repo = "m-demare/hlargs.nvim"
depends = "nvim-treesitter"
lua_add = '''
require("hlargs").setup()
'''

#コメント
[[plugins]]
repo = "numToStr/Comment.nvim"
#ユーティリティ
[[plugins]]
repo = "max397574/better-escape.nvim"
lua_add = '''
require "modules.tools.better_escape"
'''

[[plugins]]
repo = "Pocco81/auto-save.nvim"
lua_add = '''
require "modules.tools.auto-save"
'''

[[plugins]]
repo = "christoomey/vim-tmux-navigator"

#ui
[[plugins]]
repo = "folke/trouble.nvim"
lua_add = '''
require "modules.ui.trouble"
'''

[[plugins]]
repo = "j-hui/fidget.nvim"
lua_add = '''
require "modules.ui.finget"
'''

[[plugins]]
repo = "glepnir/dashboard-nvim"
lua_add = '''
require "modules.ui.dashboard"
'''

[[plugins]]
repo = "nvim-lualine/lualine.nvim"
lua_add = '''
require "modules.ui.lualine"
'''

[[plugins]]
repo = "akinsho/bufferline.nvim"
lua_add = '''
require "modules.ui.bufferline"
'''

#ファイラ―
[[plugins]]
repo = "lambdalisue/fern.vim"
[[plugins]]
repo = "lambdalisue/fern-renderer-nerdfont.vim"
[[plugins]]
repo = "lambdalisue/glyph-palette.vim"
[[plugins]]
repo = "lambdalisue/nerdfont.vim"
[[plugins]]
repo = "lambdalisue/readablefold.vim"

#スクリーンショット
[[plugins]]
repo = "narutoxy/silicon.lua"
lua_add = '''
require "modules.command.silicon"
'''

#カラースキーム
[[plugins]]
repo = "EdenEast/nightfox.nvim"
lua_add = '''
require "modules.colorScheme.nightfox"
'''
