# lsp
[[plugins]]
repo = "williamboman/mason.nvim"
[[plugins]]
repo = "williamboman/mason-lspconfig.nvim"
[[plugins]]
repo = "neovim/nvim-lspconfig"
depends = "impatient.nvim"
lua_add = '''
require "modules.completion.lspconfig"
'''

# フォーマッタ―・リンター
[[plugins]]
repo = "jose-elias-alvarez/null-ls.nvim"
depends = "plenary.nvim"
lua_add = '''
require "modules.completion.null-ls"
'''

# cmp
[[plugins]]
repo = "hrsh7th/nvim-cmp"
depends = "impatient.nvim"
lua_add = '''
require "modules.completion.cmp"
'''
[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp"
[[plugins]]
repo = "hrsh7th/cmp-buffer"
[[plugins]]
repo = "hrsh7th/cmp-path"
[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp-signature-help"
[[plugins]]
repo = "hrsh7th/cmp-nvim-lua"
[[plugins]]
repo = "hrsh7th/cmp-cmdline"
[[plugins]]
repo = "saadparwaiz1/cmp_luasnip"

#スニペット
[[plugins]]
repo = "L3MON4D3/LuaSnip"
lua_add = '''
require("luasnip.loaders.from_vscode").lazy_load {
  paths = { "./friendly-snippets" },
}
'''

# json
[[plugins]]
repo = "b0o/schemastore.nvim"
depends = "nvim-lspconfig"
