# プラグインマネージャー
[[plugins]]
repo = "Shougo/dein.vim"

# 速度上昇
[[plugins]]
repo = "lewis6991/impatient.nvim"
lua_add = '''
require('impatient')
'''

#treesitter
[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
depends = "impatient.nvim"
hook_post_update = "TSUpdate"
lua_add = '''
require "modules.editor.treesitter"
'''

# インデント
[[plugins]]
repo = "lukas-reineke/indent-blankline.nvim"
lua_add = '''
require "modules.editor.indent_blankline"
'''

# htmlのタグ
[[plugins]]
repo = "windwp/nvim-ts-autotag"

#括弧の色
[[plugins]]
repo = "p00f/nvim-ts-rainbow"

#引数の色付け
[[plugins]]
repo = "m-demare/hlargs.nvim"
lua_add = '''
require("hlargs").setup()
'''

#ユーティリティ

#コメント
[[plugins]]
repo = "numToStr/Comment.nvim"
lua_add = '''
-- コメント
vim.keymap.set("n", "<Leader>/", function()
	return vim.v.count == 0 and "<Plug>(comment_toggle_linewise_current)" or "<Plug>(comment_toggle_linewise_count)"
end, { expr = true })

vim.keymap.set("x", "<Leader>/", "<Plug>(comment_toggle_blockwise_visual)")
vim.keymap.set("n", "<leader>a", function()
	require("Comment.api").insert.linewise.eol(require("Comment.config"):get())
end)
'''

[[plugins]]
repo = "max397574/better-escape.nvim"
lua_add = '''
require "modules.tools.better_escape"
'''

[[plugins]]
repo = "Pocco81/auto-save.nvim"
lua_add = '''
require "modules.tools.auto-save"
'''

#ui
[[plugins]]
repo = "glepnir/dashboard-nvim"
lua_add = '''
require "modules.ui.dashboard"
'''

[[plugins]]
repo = "nvim-lualine/lualine.nvim"
depends = "nvim-web-devicons"
lua_add = '''
require "modules.ui.lualine"
'''


#ファイラ―
[[plugins]]
repo = "lambdalisue/fern.vim"
hook_add = "runtime vim/fern.vim"
[[plugins]]
repo = "lambdalisue/fern-renderer-nerdfont.vim"
[[plugins]]
repo = "lambdalisue/glyph-palette.vim"
[[plugins]]
repo = "lambdalisue/nerdfont.vim"
[[plugins]]
repo = "lambdalisue/readablefold.vim"

#カラースキーム
[[plugins]]
repo = "EdenEast/nightfox.nvim"
lua_add = '''
require("nightfox").setup {}
vim.cmd "colorscheme nightfox"
'''
