[[plugins]]
repo = "lewis6991/impatient.nvim"
lua_add = '''
require('impatient')
'''

# lsp
[[plugins]]
repo = "williamboman/mason.nvim"
[[plugins]]
repo = "williamboman/mason-lspconfig.nvim"
[[plugins]]
repo = "neovim/nvim-lspconfig"
depends = "impatient.nvim"
lua_add = '''
require "modules.completion.lspconfig"
'''

[[plugins]]
repo = "jose-elias-alvarez/null-ls.nvim"
on_event = "LspAttach"
depends = "plenary.nvim"
lua_add = '''
require "modules.completion.null-ls"
'''

# cmp
[[plugins]]
repo = "hrsh7th/nvim-cmp"
depends = "impatient.nvim"
lua_add = '''
require "modules.completion.cmp"
'''
[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp"
[[plugins]]
repo = "hrsh7th/cmp-buffer"
[[plugins]]
repo = "hrsh7th/cmp-path"
[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp-signature-help"
[[plugins]]
repo = "hrsh7th/cmp-nvim-lua"
[[plugins]]
repo = "hrsh7th/cmp-cmdline"
[[plugins]]
repo = "saadparwaiz1/cmp_luasnip"
[[plugins]]
repo = "b0o/schemastore.nvim"

#スニペット
[[plugins]]
repo = "L3MON4D3/LuaSnip"
lua_add = '''
require "modules.completion.luasnip"
'''

#treesitter
[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
depends = "impatient.nvim"
hook_post_update = "TSUpdate"
lua_add = '''
require "modules.editor.treesitter"
'''
# インデント
[[plugins]]
repo = "lukas-reineke/indent-blankline.nvim"
lua_add = '''
require "modules.editor.indent_blankline"
'''
# htmlのタグ
[[plugins]]
repo = "windwp/nvim-ts-autotag"

#括弧の色
[[plugins]]
repo = "p00f/nvim-ts-rainbow"

[[plugins]]
repo = "m-demare/hlargs.nvim"
lua_add = '''
require("hlargs").setup()
'''

#ユーティリティ

#コメント
[[plugins]]
repo = "numToStr/Comment.nvim"
lua_add = '''
-- コメント
vim.keymap.set("n", "<Leader>/", function()
	return vim.v.count == 0 and "<Plug>(comment_toggle_linewise_current)" or "<Plug>(comment_toggle_linewise_count)"
end, { expr = true })

vim.keymap.set("x", "<Leader>/", "<Plug>(comment_toggle_blockwise_visual)")
vim.keymap.set("n", "<leader>a", function()
	require("Comment.api").insert.linewise.eol(require("Comment.config"):get())
end)
'''

[[plugins]]
repo = "max397574/better-escape.nvim"
lua_add = '''
require "modules.tools.better_escape"
'''

[[plugins]]
repo = "Pocco81/auto-save.nvim"
lua_add = '''
require "modules.tools.auto-save"
'''

#ui
[[plugins]]
repo = "folke/trouble.nvim"
depends = "nvim-web-devicons"
lua_add = '''
require "modules.ui.trouble"
'''

[[plugins]]
repo = "glepnir/dashboard-nvim"
lua_add = '''
require "modules.ui.dashboard"
'''

[[plugins]]
repo = "nvim-lualine/lualine.nvim"
depends = "nvim-web-devicons"
lua_add = '''
require "modules.ui.lualine"
'''

[[plugins]]
repo = "akinsho/bufferline.nvim"
depends = "nvim-web-devicons"
lua_add = '''
require "modules.ui.bufferline"
'''

#ファイラ―
[[plugins]]
repo = "lambdalisue/fern.vim"
[[plugins]]
repo = "lambdalisue/fern-renderer-nerdfont.vim"
[[plugins]]
repo = "lambdalisue/glyph-palette.vim"
[[plugins]]
repo = "lambdalisue/nerdfont.vim"
[[plugins]]
repo = "lambdalisue/readablefold.vim"



#カラースキーム
[[plugins]]
repo = "EdenEast/nightfox.nvim"
lua_add = '''
require("nightfox").setup {}
vim.cmd "colorscheme nightfox"
'''
